export ZSH=/Users/ankitsultana/.oh-my-zsh
autoload -U colors && colors

source ~/.utilities/sh/upto.sh
stty start undef stop undef


setopt promptsubst
RUBY_BUILD_CACHE_PATH="/Users/ankitsultana/.rbenv/cache"

export EDITOR=vim
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin
export PYTHONPATH=$PYTHONPATH:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
export PYTHONPATH=$PYTHONPATH:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2-1.0-py2.7.egg-info

if [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
	ZSH_THEME="ankitsultana"
else
	ZSH_THEME="ankitsultana"
fi

#========== Awesome stuff below ===========#

alias g++='clang++ -std=c++11'
# When programming for say a codeforces contest
# Store the input files as 1 2 3 (without extension)
# Then compile the source code.. and run it by typing
# <run_tests 3> #if you want to run the code for 3 input files
run_tests() {
	local i=1
	while [ $i != $1 ]; do
		./a.out < $i
		i=$((i+1))
	done
	./a.out < $i
}

# Self Explanatory
alias whichgitbranch="git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3"

# A touch of Naruto
almightypush() {
	local curr_branch="$(whichgitbranch)"
	git push origin $curr_branch
	echo $curr_branch
}

submit() {
	cat $1 |pbcopy
}

templar() {
	if [ -e $1 ]
	then
		echo "File Already exists!!"
		read T
		vim $1
	else
		cp ~/.template2.cc $1
		vim $1
	fi
}


tmate() {
  open $1 -a "TextMate"
}

subl() {
	open $1 -a "Sublime Text"
}

alias gotosentdex='gotoprogramming ; cd ./Python/sentdex'

alias gotoprogramming='cd ~/Desktop/Desk/CS/Programming'

alias gotospoj='cd ~/Desktop/Desk/CS/Programming/Sport/C++/spoj/'

alias gotoimpl='gotospoj; cd ../Implementations'

plugins=(git github)
DEFAULT_USER=`whoami`
#plugins=(rails sublime web-search chucknorris github rand-quote git ruby)

# Set path for tex, python 2, python 3
export PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"

alias gotochef=/Users/ankitsultana/Desktop/Desk/CS/Programming/Sport/C++/codechef
alias gotoforces=/Users/ankitsultana/Desktop/Desk/CS/Programming/Sport/C++/CODEFORCES
export PATH="$HOME/.rbenv/bin:$PATH"

source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export NODE_PATH="/usr/local/lib/node_modules:/Users/ankitsultana/jpm:/Users/ankitsultana/jpm/node_modules"
export PATH=/usr/local/lib/node_modules:$PATH
export PATH=/Users/ankitsultana/.rbenv/shims:$PATH
export PATH=/usr/local/bin/node:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=$PATH:/Users/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iStats-1.2.0/

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
alias octave="/usr/local/octave/3.8.0/bin/octave-3.8.0 ; exit;"
